### ISSUE TITLE
Order fallback to devDeps/deps?

### ISSUE THREAD

**Issue by danielbayley** [michael-ciniawsky/postcss-load-config#1]
It might be handy to fallback to determining the plugin order from `devDependencies` then `dependencies` in the absence of `postcss.plugins` in `package.json`. No need to list them all twice _unless_ you _want_ to specify options…

**Comment by michael-ciniawsky** [comment]
hi, i think just loading plugins without proper order is a souce of error thown behaviour and unwanted results for any user and therefore should be avoided. Dependencies get ordered alphabetically, just with these 'heuristic', there's no way load-config could be aware of the use nor can it figure out where to specifiy their postion in the sequence. Getting a correct result without correct plugin order would be a 'luky punch' most of the time, while on the other hand unintended results will occur most of the time.

I currently test 'packaging' to shorten the config e.g

**postcss-package-css**
```js
let plugins = [
  {
    plugin : require('postcss-bem'),
    namespace: 'bem',
    defaults: {/* set your default here */}
  },
  ....,
  ....
]


module.exports = postcss.plugin('my-package', function (plugins, options) {
  options = options || {}

  let instance = postcss()

  // each plugin
  processors.forEach((processor) => {
    var namespaceOptions = processor.namespace in options ? options[processor.namespace] : options
    var processorOptions = {}

    Object.keys(processor.defaults).forEach((key) => {
      processorOptions[key] = processor.defaults[key]
    })

    Object.keys(namespaceOptions).forEach((key) => {
      processorOptions[key] = namespaceOptions[key]
    })

    if (namespaceOptions && !processorOptions.disable) {
      instance.use(processor.plugin(processorOptions))
    }
  })

  return instance
})
```

**package.json**
```json
"dependencies": {
  "postcss-package-css": "1.0.0"
}
```
**postcss.config.js**
```js
module.exports = {
 plugins: {
  'postcss-package-css': {
    bem: {/* overrides defaults, when specified */} || disable (omits plugin)
  }
}
```

The package idea is older than the common config approach, i have no time at the moment to work it out, but i intend to find a way where you can bundle your config into a package and then publish it on npm and install that instead.


```bash
postcss --package name
```

**Comment by danielbayley** [comment]
> i think just loading plugins without proper order is a souce of error

I agree, but I wasn't suggesting it should work from the alphabetically ordered list, but more thinking in terms of manually specifying them in the correct order, but then I suppose that falls apart if you use `npm --save`. Then again, you already have to manually order them anyway. Tricky one…

> i intend to find a way where you can bundle your config into a package and then publish it on npm and install that instead.

I like that idea.

**Comment by michael-ciniawsky** [comment]
> I agree, but I wasn't suggesting it should work from the alphabetically ordered list

No, but the pkg.dependencies object has the plugins in alphabetically order, you could of course use an array for setting the position in the sequence 
```js 
dependencies : {
   "plugin1": "*"
   "plugin2": "*"
   "plugin3": "*"
   "plugin4": "*"
   "plugin5": "*"
}
```
```js
plugins: [3, 2, 1, 4, 0] => position in postcss.plugins
```
```js
postcss([ plugin5(), plugin3(), plugin2(), plugin1(), plugin4() ]).process(css)..
```
Try to rewrite it :) its's pure brainfuck every time for just setting up some plugins, which is tedious enough.

Currently the intension for packaging is something like e.g:

**package.json**
```js
dependencies: {
   "postcss-plugin1": "*",
   "postcss-plugin2": "*",
   "postcss-plugin3": "*",
   "postcss-package1": "*"
}
```
**postcss.config.js**
```js
module.exports  = {
  options: {
    parser: "sugarss",
    from: "app.sss",
    to: "app.css",
    map: "inline"
  },
  plugins: {
   "postcss-plugin1": null,
   "postcss-plugin2": null,
   "postcss-plugin3": null,
  },
  packages: {
    "postcss-package": {
      "extend": [1, 3, 5] => set position of 'additional' plugins from postcss.plugins (needs ux improvements)
      "import": null, => use namespace without postcss-prefix, because order of package plugins is 
      "bem": {},         already defined in the package
      "nested": null
    }
  }
}
```

So someone can spread additional plugins in his 'standard plugin package'

```js 
postcss([ import(), plugin1(), bem(), plugin2(), nested(), plugin3() ]).process(css)...
```

If you have any concerns or a different idea please share you thoughts :)
