### ISSUE TITLE
Update `cosmiconfig`

### ISSUE THREAD

**Issue by simonjoom** [michael-ciniawsky/postcss-load-config#109]
i found an issue with last babel7 ,

don't know where it was from 
but when i installed the last cosmiconfig 3  it was resolved .. maybe you should to update it in your repo

**Comment by michael-ciniawsky** [comment]
I'm aware of the required `cosmiconfig` update and will do it as soon as possible

**Comment by mic159** [comment]
Damn, this is blocking install for me now.

cosmiconfig 2.x has a dependency on an old version of require-from-string, which is no longer available in npm registry.
cosmiconfig 3.0.1 updated require-from-string to the latest version back on 18 Sep 2017.
