### ISSUE TITLE
Failed to install postcss-load-config on centos No compatible version found: require-from-string@^1.1.0

### ISSUE THREAD

**Issue by tovinayv** [michael-ciniawsky/postcss-load-config#121]
-bash-4.1$ npm install postcss-load-config
npm ERR! Linux 2.6.32-642.6.2.el6.x86_64
npm ERR! argv "/dbc/blr-dbc404/vinayv/nodejs/lin64/bin/node" "/dbc/blr-dbc404/vinayv/nodejs/lin64/bin/npm" "install" "postcss-load-config"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: require-from-string@^1.1.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 2.0.2
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'cosmiconfig'
npm ERR! notarget

npm ERR! Please include the following file with any support request:

-bash-4.1$ lsb_release -a
LSB Version: :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description: CentOS release 6.6 (Final)
Release: 6.6
Codename: Final

-bash-4.1$ npm -v
3.10.10
-bash-4.1$ node -v
v6.9.4

**Comment by michael-ciniawsky** [comment]
https://github.com/npm/registry/issues/255#issuecomment-355771177
