### ISSUE TITLE
Using loader.addDependency inside config

### ISSUE THREAD

**Issue by franciscolourenco** [michael-ciniawsky/postcss-load-config#134]
## Problem

Plugins like `postcss-simple-vars` or `postcss-properties` etc allow variables to be specified. These variables are usually imported from other files. Even though webpack reloads when `postcss.config.js` is modifier, the same doesn't happen for variable files imported in `postcss.config.js`. Is there a way to access [`loader.addDependency`](https://webpack.js.org/api/loaders/#this-adddependency) so that imported files can be added manually? Or is there another way to achieve this?

**Comment by michael-ciniawsky** [comment]
`postcss-loader >= 2.1.4` restored the loader context on the `config.ctx`, so `addDependecy` should be available now (`ctx.webpack.addDependency`)
