### ISSUE TITLE
Using webpack config instead of postcss

### ISSUE THREAD

**Issue by ai** [michael-ciniawsky/postcss-load-config#16]
I created a webpack test case: https://github.com/ai/webpack2-postcss-test

It runs PostCSS config test by `webpack --config webpack2.config.js`.

And I got error:

```
> webpack --config webpack2.config.js

Hash: 4c7045863603cdc062c1
Version: webpack 2.1.0-beta.25
Time: 401ms
    Asset     Size  Chunks             Chunk Names
./app2.js  2.81 kB       0  [emitted]  main
   [1] ./index.js 33 bytes {0} [built]
    + 1 hidden modules

ERROR in ./index.css
Module build failed: TypeError: Cannot convert undefined or null to object
    at loadPlugins (/home/ai/Dev/test/node_modules/postcss-load-plugins/lib/loadPlugins.js:26:10)
    at /home/ai/Dev/test/node_modules/postcss-load-config/index.js:19:18
 @ ./index.js 1:10-32
```

When I debuged `loadConfig` function in `postcss-load-config` I got that it has in `result`:

```js
{ config: 
   { entry: './index.js',
     output: { filename: './app2.js' },
     module: { rules: [Object] } },
  filepath: '/home/ai/Dev/test/webpack2.config.js' }
```

Seems like cosmiconfig got webpack config because it track `--config` argument. I think it is not expected behavior.

@davidtheclark I am not sure, in what repo I should create a issue. If cosmiconfig really takes arguments, we should add option to do it only from `stylelint`/`postcss` CLI tools and doesn’t do it from webpack/gulp plugins.

**Comment by michael-ciniawsky** [comment]
hmm, maybe  cosmiconfig v2.0.0 solves this, because ```var config = cosmiconfig('postcss')``` is it's own instance now, but in general it should look only for postcss* only normally that worked. postcss-load-* is finished now, I released it tonight test it with postcss-loader and resolve the remaining issues, but first things first, little more time please :)

**Comment by davidtheclark** [comment]
> Seems like cosmiconfig got webpack config because it track --config argument. I think it is not expected behavior.

You can turn this off with the `argv` argument. That's what we're doing in stylelint.

**Comment by michael-ciniawsky** [comment]
@davidtheclark  :+1:

**Comment by ertrzyiks** [comment]
I've just checked and ```return config('postcss', {argv: 'postcss-config'})``` seems to actually help

**Comment by ai** [comment]
Issues seems like fixed in beta. Thanks!
