### ISSUE TITLE
Custom plugins examples

### ISSUE THREAD

**Issue by ai** [michael-ciniawsky/postcss-load-config#17]
We need to add examples, how to set custom plugins in config. Like `./my-plugin`.

This config doesn’t work:

```js
module.exports = {
  plugins: {
    './postcss-plugin': 2
  }
}
```

```
Module build failed: Error: Cannot find module './postcss-plugin'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at load (/home/ai/Dev/test/node_modules/postcss-load-plugins/lib/loadPlugins.js:21:50)
    at /home/ai/Dev/test/node_modules/postcss-load-plugins/lib/loadPlugins.js:27:18
    at Array.forEach (native)
    at loadPlugins (/home/ai/Dev/test/node_modules/postcss-load-plugins/lib/loadPlugins.js:26:24)
    at /home/ai/Dev/test/node_modules/postcss-load-config/index.js:20:18
```

This config doesn’t work too:

```js
module.exports = {
  plugins: [
    require('./postcss-plugin')(2)
  ]
}
```

```
Module build failed: Error: Cannot find module '0'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at load (/home/ai/Dev/test/node_modules/postcss-load-plugins/lib/loadPlugins.js:21:50)
    at /home/ai/Dev/test/node_modules/postcss-load-plugins/lib/loadPlugins.js:27:18
    at Array.forEach (native)
    at loadPlugins (/home/ai/Dev/test/node_modules/postcss-load-plugins/lib/loadPlugins.js:26:24)
    at /home/ai/Dev/test/node_modules/postcss-load-config/index.js:20:18
```

**Comment by michael-ciniawsky** [comment]
yep, the question is if it not better to 'enforce' one format, since using a function  as config is now possible ?

**Comment by ai** [comment]
Yeap, I think one format is better, than multiple. It is easy to show one format in docs, rather than "use this format for this case, and that format for different".

**Comment by michael-ciniawsky** [comment]
i will try 

```js
modules.exports = {
 parser: ...,
 plugins: [
   require('postcss-plugin')
 ]
}
```
simply 'passthrough' the array, but it's a potential error pit, if to fragile I leave it for now, anything should be possible with 'standard formatted' ```config()/config``` by now :)

**Comment by ai** [comment]
Array in JS syntax and object in package.js on and JSON config? Looks good.

**Comment by michael-ciniawsky** [comment]
config.plugins can be an {Object} or an {Array} in JS, `.postcssrc` (JSON) is an standard format {Object} only during the lack of `require()`, the array will be checked if plugins are `required` and returned

**Comment by michael-ciniawsky** [comment]
When finished is ping you and you can finally approve it before npm publish ? :)

**Comment by ai** [comment]
@michael-ciniawsky we had some problem with array. I will retest it, when you ping me with 1.0 pre-release.

Sure, ping me before release.

**Comment by michael-ciniawsky** [comment]
:+1: yep maybe leave it enterily abd curently `postcss-load-config v1.0.0-alpha4` there is no array support 😛

**Comment by michael-ciniawsky** [comment]
Using an Array works know, this should resolve the issue requiring a local plugin (develop, testing) aswell. 

```js
module.exports = (ctx) => {
 parser: 'sugarss',
 plugins: [
   require('./postcss-dev')(ctx.dev)
 ] 
}
```

**Comment by ai** [comment]
@michael-ciniawsky I saw that you updated examples. They become much better.

Few extra changes, that I suggest:

1. Make first example simpler. Most of developers will not use context. Let’s move context example to the bottom of doc.
2. Split array and object example with explicit “or you can use arrays”

**Comment by michael-ciniawsky** [comment]
@ai 👍
