### ISSUE TITLE
Extending one config with another

### ISSUE THREAD

**Issue by Grawl** [michael-ciniawsky/postcss-load-config#179]
Can't find a way to extend config like I do it with `.eslintrc` https://eslint.org/docs/user-guide/configuring#extending-configuration-files

**Comment by michael-ciniawsky** [comment]
It's deliberately not supported atm. What's the use case your are having in particular?

**Comment by Grawl** [comment]
As a workaround, I merge configs with `deepmerge` like this:

`postcss.config.js` in project:

```js
const extendBaseConfig = require('my-postcss-config')
module.exports = ctx => extendBaseConfig(ctx, ctx => {
	return {
		plugins: {
			'postcss-easing-gradients': {},
		}
	}
})
```

`my-postcss-config/index.js`:

```js
const base = require('./postcss.config')
const merge = require('deepmerge')
module.exports = (ctx, config) => merge([ base(ctx), config(ctx) ])
```

`my-postcss-config/postcss.config.js`:

```js
module.exports = ctx => {
	return {
		plugins: {
			'postcss-axis': {},
			'postcss-short': {},
			'postcss-position-alt': {},
			'autoprefixer': {},
		},
	}
}
```

**Comment by michael-ciniawsky** [comment]
That's one option and likely better to leave it up to the user to 'extend/merge' parts of his/her config in the way it's intended. Another option would be to wrap plugins as a plugin (e.g`cssnano` or `postcss-preset-env`) and add that plugin ('preset') to the config instead. The reason why I decided against adding ayn kind of `extend` to `postcss-load-config` directly is that plugin order matters

**Comment by Grawl** [comment]
So, I am doing things right or wrong?

**Comment by michael-ciniawsky** [comment]
Yeah I think so, you have the full spectrum of JS at our disposal :). Using `deepmerge` could eventually be avioded but that's enterily preference. Every `require` will of course add a bit of overhead, but that's just how it works...

```js
// preset1.js
const preset1 = (ctx) => ({
  a: { option: 1 },
  b: {}
})

// preset2.js
const preset2 = (ctx) => ({
  a: { option: 2 },
  c: {}
})

// $PROJECT/postcss.config.js
const preset1 = require('./preset1.js')
const preset2 = require('./preset2.js')

const config = (ctx) => ({
  plugins: {
    ...preset1(ctx),
    ...preset2(ctx)
  }
})
```

**Comment by Grawl** [comment]
So I can add one config as plugin in another config?

**Comment by Grawl** [comment]
Answer to my previous question: no. Michael just shows how Object Rest Spread works.

Just checked it out:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/846774/50944680-1d18c000-14dd-11e9-9412-f6f5f3193747.png">

Look at `{c}`, where `e` field from `obj1` is missing in `{merged}`. So, Object Rest Spread is one-level merge.
