### ISSUE TITLE
Update cosmiconfig to latest version

### ISSUE THREAD

**Issue by followdarko** [michael-ciniawsky/postcss-load-config#184]
Cosmiconfig below `5.0.0` has` js-yaml` deps package that has vulnerability issue. So please update it that postcss-load-config has no vulnerabilitiy too.

**Comment by bmatcuk** [comment]
I've got you covered in my PR =)

**Comment by michael-ciniawsky** [comment]
Released in [`v2.1.0`](https://github.com/michael-ciniawsky/postcss-load-config/releases/tag/v2.1.0)

**Comment by dskecse** [comment]
@michael-ciniawsky it looks like it hasn't gotten to the v2.1.0 release https://github.com/michael-ciniawsky/postcss-load-config/blob/master/package.json#L20 as `cosmiconfig` is still at v5.0.0

**Comment by michael-ciniawsky** [comment]
@dskecse `cosmiconfig: ^5.0.0` is the latest `major` version available? Note the `^` which should install the latest version in the `minor/patch` range according to `semver` e.g `v5.2.1` (currently the latest release). Which specific issue do you have?

**Comment by dskecse** [comment]
@michael-ciniawsky my bad, I somehow slipped through the `^` symbol and only noticed the `5.0.0`. I can confirm it worked when I updated the `postcss-loader`.
