### ISSUE TITLE
Failing because loadOptions and loadPlugins was renamed

### ISSUE THREAD

**Issue by farwayer** [michael-ciniawsky/postcss-load-config#24]
https://github.com/michael-ciniawsky/postcss-load-options/commit/372bfd2b278021268cd115bdff5453c179958955
https://github.com/michael-ciniawsky/postcss-load-plugins/commit/39125f0ae3b564fd2868cf2ec719426d9fcf018d

**Comment by michael-ciniawsky** [comment]
Fixed in `postcss-load-config v1.0.0-beta`
