### ISSUE TITLE
Fix behaviour when config loading failes

### ISSUE THREAD

**Issue by farwayer** [michael-ciniawsky/postcss-load-config#26]
I have no postcss configs. And several log messages at webpack log as result of using postcss-loader.

```js
TypeError: Cannot read property 'config' of null
    at .../node_modules/postcss-load-config/index.js:44:22
```

**Comment by ai** [comment]
@michael-ciniawsky +1

Maybe we need to add check is `result` a `undefined` before 44 line

**Comment by michael-ciniawsky** [comment]
```diff
+ result === undefined ? { config: {} } : result
- result = result.config || {}
```

should do the job

**Comment by ai** [comment]
We could close it?

**Comment by michael-ciniawsky** [comment]
@ai yep :)

**Comment by kevinlaw91** [comment]
Hello. I still get this problem. I think this should be the correct fix instead... :wink: 

```diff
+ result = (result === undefined) ? { config: {} } : result
- result === undefined ? { config: {} } : result
```

**Comment by azrael25** [comment]
Yeah, you forgot to assign a value to a variable. And one more thing: `cosmiconfig().load()` returns `null` if config not found. So I assume you need to use `!result` instead of `result === undefined`.

**Comment by michael-ciniawsky** [comment]
@kevinlaw91 @azrael25  :+1: fix it asap
