### ISSUE TITLE
node.js 0.12 support

### ISSUE THREAD

**Issue by ai** [michael-ciniawsky/postcss-load-config#27]
Right now `postcss-loader` falls on node.js 0.12 with:

```
Error: /home/travis/build/postcss/postcss-loader/node_modules/postcss-load-config/index.js:7
const config = require('cosmiconfig')
^^^^^
Use of const in strict mode.
```

I know that we could ignore node.js 0.12, but fix will be so small. I think it is better to support it in this case. Anyway we have a lot of users on 0.12.

**Comment by ai** [comment]
Also we may need to test other `postcss-load-*` packages.

**Comment by michael-ciniawsky** [comment]
yep, I dropped node v0.12 support, bc of cosmiconfig a similiar 'issue'. If cosmiconfig is open to suppprt node v0.12, I fixed it of course. Either babel preinstall/prepublish hook or back to `var` then.

**Comment by ai** [comment]
@davidclark Really? :( You dropped node.js 0.12 support only for `const`?

OK, I could drop node.js 0.12 support in `postcss-loader`. But I think we should care about users more, than about functional-style trends.

**Comment by michael-ciniawsky** [comment]
@ai Yep, basically agreed, but on the other hand node v0.12 support ends Jan 2017 :), it's a bit early to drop it nevertheless, I can ask/check if webpack 2 release will be node v4+ anyways.

**Comment by ai** [comment]
Ok. Good point.

**Comment by michael-ciniawsky** [comment]
@ai so you are fine with dropping node v0.12 it for now ? In case that many users start complaining about it, I prepare/keep track of adding node v0.12 back on both `cosmiconfig` && `postcss-load-config`, it should be trivial :)

**Comment by ai** [comment]
You convinced me about node.JS 0.12 support, but I remembered other problem.

When we integrate config to core, `const` will fall Safari (even if config code will not be executed in browser).

So we need to fix it. I will create issue in comsiconf.

**Comment by ai** [comment]
Comsiconf issue: https://github.com/davidtheclark/cosmiconfig/issues/35

**Comment by ai** [comment]
@michael-ciniawsky Cosmiconfig fixed node.js 0.12 support ;)

**Comment by michael-ciniawsky** [comment]
@ai 👍
@davidclark Thx for reverting && comsiconfig in general, appreciated :+1
