### ISSUE TITLE
Published npm version does not match source

### ISSUE THREAD

**Issue by ctrlplusb** [michael-ciniawsky/postcss-load-config#34]
Here is the published version:
https://unpkg.com/postcss-load-config@1.0.0-rc/index.js

Note the following code:

```js
  return config('postcss', options)
    .load(path)
    .then(function (result) {
      if (result === undefined) {
        console.log(
          'PostCSS Config could not be loaded. Please check your PostCSS Config.'
        )
      }

      result === undefined ? { config: {} } : result
      result = result.config

      return result
    })
```

Compare that to the source in this github repo:

```js
  return config('postcss', options)
    .load(path)
    .then(function (result) {
      if (!result) {
        console.log(
          'PostCSS Config could not be loaded. Please check your PostCSS Config.'
        )
      }

      return result ? result.config : {}
    })
```

Looks like a publish failed somewhere... :(

The current published version breaks when I run it due to function parameter reassignment. I wanted to do a PR to fix this but then noticed it's already fixed in the source.  Then I noticed the source version does not match the published version.

**Comment by michael-ciniawsky** [comment]
done 👍  :)
