### ISSUE TITLE
Specify path to config file

### ISSUE THREAD

**Issue by SimenB** [michael-ciniawsky/postcss-load-config#55]
## Problem

I want to place my `postcss.config.js` in a `config` dir, not in the root of my project, but then it's not discovered.

## Details

It will be next to the config used by webpack if the postcss-loader could be told that, but maybe a key in package.json could point to it?

## Environment

Please provide information about your environment.

| OS              | Node      | yarn       | PostCSS   |
|:---------------:|:---------:|:---------:|:---------:|
| macOS@10.12.1 | 6.9.1 | 0.18.0 | postcss-loader: 1.2.0 |

**Comment by michael-ciniawsky** [comment]
@SimenB 👋 Shipped with `postcss-loader`> v1.2.0

```js
{
  test: /\.css/,
  use: [ 
    { loader: 'css-loader', options: { importLoaders: 1 } }, 
    { loader: 'postcss-loader', options: { config: 'alternative/path/to/postcss.config.js' } }
  ]
}
```

**Comment by SimenB** [comment]
Oh, there you go! I'll give it a try later today.
Didn't find any mention of it here or in https://github.com/postcss/postcss-loader/blob/master/README.md

**Comment by michael-ciniawsky** [comment]
It's not documented atm, we first want to try out, if there is a programmtic solution for cases like that (e.g if config folder in directory, try searching there aswell).

**Comment by SimenB** [comment]
Yep, got it working, thanks!

Just one small nit with it, but it works 😄  postcss/postcss-loader#147

**Comment by mrwade** [comment]
For those using webpack 2.2, you'll need to use `query` instead of `options`. This tripped me up for a bit.

```js
{
  test: /\.css/,
  loaders: [ 
    { loader: 'css-loader', query: { importLoaders: 1 } }, 
    { loader: 'postcss-loader', query: { config: 'alternative/path/to/postcss.config.js' } }
  ]
}
```

**Comment by vjpr** [comment]
Anyone stumbling across this...the query string params have changed.

You now need to use `{config: {path: '/path/to/config'}`.

**Comment by michael-ciniawsky** [comment]
@vjpr Yep, I changed it in `postcss-loader` [v2.0.0](https://github.com/postcss/postcss-loader/releases/tag/v2.0.0) :)
