### ISSUE TITLE
Making use of babel transpilation on postcss.config.js

### ISSUE THREAD

**Issue by felixsanz** [michael-ciniawsky/postcss-load-config#58]
In webpack you can transpile the config files by just using `babel.js` extension instead of `.js` (webpack-dev.babel.js for example).

Would be nice if postcss.config.js runs the same. Maybe postcss.config.babel.js. This way we can use js syntax through babel.

**Comment by michael-ciniawsky** [comment]
Sry but I don't intend to support this out-of-the-box, the babel deps would outweigh the module size and most depending modules use `postcss-load-config` on a **per file** basis, so the transpilation step could be a perf issue. You could try using `babel-register` and see if that works :stuck_out_tongue:
