### ISSUE TITLE
Don't write errors to stdout

### ISSUE THREAD

**Issue by RyanZim** [michael-ciniawsky/postcss-load-config#60]
## Problem

postcss-load-config writes errors to stdout: https://github.com/michael-ciniawsky/postcss-load-config/blob/master/index.js#L72

This has several problems:

1. It takes away control of error handling from library users.
1. Since errors are written to stdout (not stderr), if an error is produced when running this in a CLI context and using output redirection (`>` or `|`), the error will go unnoticed.
1. It also makes it nearly impossible for you to test your error cases.

Libraries shouldn't include a `catch` block at the end of promise chains unless they are ignoring the error, or re-trying after a timeout, etc.

Also https://github.com/michael-ciniawsky/postcss-load-config/blob/master/index.js#L49 should throw an error (that will follow the promise chain) instead of logging.

---

https://github.com/michael-ciniawsky/postcss-load-plugins & https://github.com/michael-ciniawsky/postcss-load-options have the same problem.

**Comment by michael-ciniawsky** [comment]
@RyanZim 

```js
....
 if (!result) {
    throw new Error(
      'PostCSS Config could not be loaded. Please check your PostCSS Config.'
    )
 }
....

.then(...)
.catch(console.err) 
```

?

**Comment by RyanZim** [comment]
@michael-ciniawsky That should do it for `load-config`. Still needs fixed in `load-plugins` & `load-options`. (catch blocks need changed)

**Comment by RyanZim** [comment]
BTW, should config not loaded throw an error at all? In the case of postcss-cli, if the user is using command line flags, no config is perfectly fine.

**Comment by RyanZim** [comment]
Also should mention that this is a breaking change.

**Comment by michael-ciniawsky** [comment]
> Still needs fixed in load-plugins & load-options. (catch blocks need changed)

How ? :)

> BTW, should config not loaded throw an error at all? In the case of postcss-cli, if the user is using command line flags, no config is perfectly fine.

Yes, but for other build tools its not 😛 . `postcss-load-config` is 'forgiving' in terms of returning defaults `plugins: [], options: {}` when no config file found, but there will be no transform then, which on the other hand could lead to confusion.

**Comment by RyanZim** [comment]
@michael-ciniawsky Sorry, I was incorrect in what I said earlier, there should not be a catch block at all, control of handling errors should be the library consumer.

**Comment by RyanZim** [comment]
> postcss-load-config is 'forgiving' in terms of returning defaults plugins: [], options: {} when no config file found, but there will be no transform then, which on the other hand could lead to confusion.

True. Perhaps it would have been wiser to return `null` like cosmiconfig does. The other way to mak this play better with postcss-cli is to allow setting an option `warnOnNoConfig` or similar.

**Comment by michael-ciniawsky** [comment]
@RyanZim 

if no config or plugin loading errors are thrown
```js
// index.js
if (!result) {
  throw new ReferenceError(
    'PostCSS Config could not be loaded. Please check your PostCSS Config.'
   )
}

// lib/plugins.js
if (
  !(typeof plugin === 'object' && Array.isArray(plugin.plugins) || typeof plugin === 'function')
) {
  throw new TypeError(
    'Invalid PostCSS Plugin found. Please check your PostCSS Config'
  )
}
```

this should work as expected correct?

```js
postcssrc(ctx)
  .then((config) => config)
  .catch(console.err) // ? 
```

> Perhaps it would have been wiser to return null like cosmiconfig does. The other way to make this play better with postcss-cli is to allow setting an option warnOnNoConfig or similar.

Ok I will think about some solution, not in favour of adding addtional options but maybe unavoidable here. Nevertheless `warn/log`  option + return defaults || hard fail as go to for now.

**Comment by RyanZim** [comment]
> this should .catch it and work as expected correct?

Yup, that should work. The only thing I would change is to throw just a regular `Error` for `PostCSS Config could not be loaded.`, instead of a `ReferenceError`.

> not in favour of adding addtional options but maybe unavoidable here. 

I understand. I _could_ hack together a solution something like this:
```
postcssrc(ctx)
  .then((config) => config)
  .catch(err => {
    if(err.message.indexOf("PostCSS Config could not be loaded") !== -1) console.error(err)
  })
```
This would filter that specific error out. However, this is still a hack; it would break if you ever change your error message.

**Comment by RyanZim** [comment]
@michael-ciniawsky What's the status of this?

**Comment by michael-ciniawsky** [comment]
@RyanZim Released in `v1.1.0`. Feel free to reopen here, if there is any mistake/undesired behavior

**Comment by RyanZim** [comment]
LGTM. This technically should have been released as a breaking change, but...

**Comment by michael-ciniawsky** [comment]
@RyanZim Yep, the only implementation in the wild is `postcss-loader` which had problems with the 'old' error handling anyways and is already updated, just fine 😛
