### ISSUE TITLE
using webpack context path

### ISSUE THREAD

**Issue by FourwingsY** [michael-ciniawsky/postcss-load-config#65]
## Problem

If i use `webpack.LoaderOptionsPlugin()`, there is a independent "context" fields.
```
new webpack.LoaderOptionsPlugin({
  options: {
    context: path.join(APP_DIR, "app/assets"),
    postcss: function(webpack) {
      return [plugins]
    }
  }
})
```
I can modify that context, and postcss use it. 

But if i use `postcss.config.js`, there is no options for independent context. 
Postcss will just using webpack's context, not it's own context.

maybe, postcss.config.js can also handle that context like
```
module.exports = (ctx) => ({
  context: path.join(APP_DIR, "app/assets"),
  plugins: {
    ...
  }
})
```

**Comment by michael-ciniawsky** [comment]
```js
module.exports = (ctx) => ({
   console.log(ctx.webpack) // Webpack Loader API => this.resourcePath etc.
})
```

@FourwingsY The webpack Context is on `ctx.webpack`. What do you mean exactly by own context, maybe I'm missing the point here :)?

**Comment by FourwingsY** [comment]
@michael-ciniawsky Sorry, i might be misusing postcss-smart-import. Thanks for your example!

**Comment by michael-ciniawsky** [comment]
@FourwingsY I highly recommend using  `postcss-import` v9+ instead of `postcss-smart-import` during the fact that `postcss-loader` is able to watch your `@import` *automatically* then

```js
import imports from 'postcss-import'

postcss([ imports() ]).process('index.css', options)
  .then((result) => {
      result.messages
        .filter((msg) => msg.type === 'dependency ? msg : '')
        .forEach((dependency) => loader.addDependency(dependency.file)) // @import's
  })
```
